# Generated by Django 5.2.7 on 2025-12-08 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regface', '0013_alter_shift_shift_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipFieldConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payslip_field_configs', to='regface.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_field_configs', to='regface.location')),
            ],
            options={
                'ordering': ['config_name'],
                'unique_together': {('location', 'config_name')},
            },
        ),
        migrations.CreateModel(
            name='PayslipTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='payslip_logos/')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('header_text', models.CharField(blank=True, max_length=200, null=True)),
                ('header_color', models.CharField(default='#1e40af', max_length=7)),
                ('header_alignment', models.CharField(default='center', max_length=10)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('footer_color', models.CharField(default='#64748b', max_length=7)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('page_size', models.CharField(default='A4', max_length=10)),
                ('orientation', models.CharField(default='portrait', max_length=10)),
                ('font_size', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payslip_templates', to='regface.user')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_template', to='regface.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayslipField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_code', models.CharField(max_length=50)),
                ('field_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('INFO', 'Information')], max_length=20)),
                ('value_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Gross'), ('FIXED', 'Fixed Amount'), ('CALCULATION', 'Calculation Script')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('display_order', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('default_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('field_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='payslip.payslipfieldconfig')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('field_config', 'field_code')},
            },
        ),
        migrations.CreateModel(
            name='PayslipRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('working_days', models.IntegerField(default=0)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_values', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payslips', to='regface.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='regface.employee')),
                ('field_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payslip.payslipfieldconfig')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payslips', to='regface.user')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payslip.paysliptemplate')),
            ],
            options={
                'ordering': ['-generated_on'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
