# Generated by Django 5.2.7 on 2025-12-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysliprecord',
            name='holiday_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paysliprecord',
            name='paid_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paysliprecord',
            name='unpaid_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paysliprecord',
            name='weekoff_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paysliprecord',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paysliprecord',
            name='present_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
