# Generated by Django 5.2.7 on 2025-12-15 11:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regface', '0014_employee_aadhaar_number_employee_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWeekoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekoff_pattern', models.CharField(blank=True, choices=[('SUNDAY', 'Every Sunday'), ('MONDAY', 'Every Monday'), ('TUESDAY', 'Every Tuesday'), ('WEDNESDAY', 'Every Wednesday'), ('THURSDAY', 'Every Thursday'), ('FRIDAY', 'Every Friday'), ('SATURDAY', 'Every Saturday'), ('SATURDAY_SUNDAY', 'Saturday & Sunday'), ('FRIDAY_SATURDAY', 'Friday & Saturday'), ('SUNDAY_MONDAY', 'Sunday & Monday'), ('CUSTOM', 'Custom Pattern')], max_length=50, null=True)),
                ('custom_days', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_weekoffs', to='regface.user')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_weekoff', to='regface.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_weekoffs', to='regface.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type_name', models.CharField(max_length=100)),
                ('leave_code', models.CharField(max_length=20)),
                ('is_paid', models.BooleanField(default=True)),
                ('max_days_per_year', models.IntegerField(blank=True, null=True)),
                ('carry_forward_allowed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_types', to='regface.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='regface.location')),
            ],
            options={
                'ordering': ['leave_type_name'],
                'unique_together': {('location', 'leave_code')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_leaves', to='regface.user')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='regface.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='regface.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='regface.location')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('total_allocated', models.IntegerField()),
                ('used_days', models.IntegerField(default=0)),
                ('pending_days', models.IntegerField(default=0)),
                ('carry_forward_from_previous', models.IntegerField(default=0)),
                ('available_days', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='regface.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='regface.location')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type'],
            },
        ),
        migrations.CreateModel(
            name='LocationWeekoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekoff_pattern', models.CharField(blank=True, choices=[('SUNDAY', 'Every Sunday'), ('MONDAY', 'Every Monday'), ('TUESDAY', 'Every Tuesday'), ('WEDNESDAY', 'Every Wednesday'), ('THURSDAY', 'Every Thursday'), ('FRIDAY', 'Every Friday'), ('SATURDAY', 'Every Saturday'), ('SATURDAY_SUNDAY', 'Saturday & Sunday'), ('FRIDAY_SATURDAY', 'Friday & Saturday'), ('SUNDAY_MONDAY', 'Sunday & Monday'), ('CUSTOM', 'Custom Pattern')], max_length=50, null=True)),
                ('custom_days', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_location_weekoffs', to='regface.user')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_weekoff', to='regface.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('HOLIDAY', 'Holiday'), ('WEEKOFF', 'Weekoff'), ('LEAVE', 'Leave')], max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('marked_on', models.DateTimeField(auto_now_add=True)),
                ('is_override', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_attendances', to='regface.employee')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_attendances', to='leave.leaverequest')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_attendances', to='regface.location')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_manual_attendances', to='regface.user')),
            ],
            options={
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOffDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('off_date', models.DateField()),
                ('off_type', models.CharField(choices=[('WEEKOFF', 'Weekly Off'), ('COMP_OFF', 'Compensatory Off'), ('PERSONAL_HOLIDAY', 'Personal Holiday'), ('SPECIAL', 'Special Off')], default='WEEKOFF', max_length=50)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_off_days', to='regface.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_days', to='regface.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_off_days', to='regface.location')),
            ],
            options={
                'ordering': ['off_date'],
                'indexes': [models.Index(fields=['employee', 'off_date'], name='leave_emplo_employe_519ebc_idx'), models.Index(fields=['location', 'off_date'], name='leave_emplo_locatio_929497_idx')],
                'unique_together': {('employee', 'off_date', 'off_type')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holiday_name', models.CharField(max_length=200)),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('NATIONAL', 'National'), ('LOCAL', 'Local'), ('RELIGIOUS', 'Religious'), ('OTHER', 'Other')], default='NATIONAL', max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to='regface.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='regface.location')),
            ],
            options={
                'ordering': ['holiday_date'],
                'indexes': [models.Index(fields=['location', 'holiday_date'], name='leave_holid_locatio_4a6ff4_idx')],
                'unique_together': {('location', 'holiday_date', 'holiday_name')},
            },
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='leave_leave_employe_158458_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='leave_leave_status_74e6de_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee', 'year'], name='leave_leave_employe_18fb87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='manualattendance',
            index=models.Index(fields=['employee', 'attendance_date'], name='leave_manua_employe_e699c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manualattendance',
            unique_together={('employee', 'attendance_date')},
        ),
    ]
