# Generated by Django 5.2.7 on 2025-12-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeWeekoff',
        ),
    ]
