# Generated by Django 5.2.7 on 2025-12-16 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_delete_employeeweekoff'),
        ('regface', '0014_employee_aadhaar_number_employee_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationweekoff',
            name='weekoff_pattern',
        ),
        migrations.AddField(
            model_name='locationweekoff',
            name='weekoff_patterns',
            field=models.JSONField(blank=True, default=list, help_text="Array of selected patterns, e.g., ['SUNDAY', 'ODD_SATURDAY']. Multiple patterns can be selected."),
        ),
        migrations.CreateModel(
            name='EmployeeWeekoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekoff_patterns', models.JSONField(blank=True, default=list, help_text="Array of selected patterns, e.g., ['SUNDAY', 'ODD_SATURDAY']. Multiple patterns can be selected.")),
                ('custom_days', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_weekoffs', to='regface.user')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_weekoff', to='regface.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_weekoffs', to='regface.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
