# Generated by Django 5.2.7 on 2025-12-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_locationweekoff_weekoff_pattern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeweekoff',
            name='custom_days',
        ),
        migrations.RemoveField(
            model_name='locationweekoff',
            name='custom_days',
        ),
    ]
