# Generated by Django 5.2.7 on 2025-12-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_remove_employeeweekoff_custom_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeOffDay',
        ),
    ]
