# Generated by Django 5.2.7 on 2025-11-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='type',
            field=models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out')], default='checkin', max_length=10),
        ),
    ]
