# Generated by Django 5.2.7 on 2025-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regface', '0002_attendancelog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
