# Generated by Django 5.2.7 on 2025-11-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regface', '0004_payrollrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='deduction_per_day',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
