# Generated by Django 5.2.7 on 2025-11-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regface', '0005_employee_base_salary_employee_deduction_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='deduction_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='esi_deduction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='pf_deduction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
