# Generated by Django 5.2.7 on 2025-11-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regface', '0006_payrollrecord_deductions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrecord',
            name='deduction_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
