# Generated by Django 5.2.7 on 2025-11-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regface', '0009_attendancelog_location_shift_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
