# Generated by Django 5.2.7 on 2025-11-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regface', '0012_alter_shift_shift_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
