# Generated by Django 5.2.7 on 2025-12-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regface', '0019_shift_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_from_date',
            field=models.DateField(blank=True, help_text='Date from which the assignment is effective', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_to_date',
            field=models.DateField(blank=True, help_text='Date until which the assignment is effective', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='sites', to='regface.shift'),
        ),
    ]
