# Generated by Django 5.2.7 on 2026-01-05 08:03

from django.db import migrations, models


def set_user_timezones(apps, schema_editor):
    """Set default timezone for all users and Malaysia timezone for specific user"""
    User = apps.get_model('regface', 'User')
    # Set Malaysia timezone for calviynz@act.com
    User.objects.filter(email='calviynz@act.com').update(timezone='Asia/Kuala_Lumpur')
    # All other users already have default 'Asia/Kolkata' from the field definition


class Migration(migrations.Migration):

    dependencies = [
        ('regface', '0020_assignment_assignment_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text="User's timezone (e.g., Asia/Kolkata, Asia/Kuala_Lumpur)", max_length=50),
        ),
        migrations.RunPython(set_user_timezones, migrations.RunPython.noop),
    ]
